### ISSUE TITLE
mirror request

### ISSUE THREAD

**Issue by thats-how-you-get-ants** [curseforge-mirror/.github#1]
request for;
BugGrabber https://www.curseforge.com/wow/addons/bug-grabber
ElitismHelper https://github.com/amki/ElitismHelper (not packaged correctly for wowup)
WorldQuestTracker https://github.com/Tercioo/World-Quest-Tracker (not packed correctly for wowup)

And thank you.

**Comment by srhinos** [comment]
Already got repos for [BugGrabber](https://github.com/curseforge-mirror/bug-grabber)] and [WorldQuestTracker](https://github.com/curseforge-mirror/world-quest-tracker)] but [ElitismHelper should be up here](https://github.com/curseforge-mirror/elitismhelper)] in a few seconds!
