### ISSUE TITLE
[REQ] OmniCD Bug Report

### ISSUE THREAD

**Issue by tw1ZTER** [curseforge-mirror/.github#103]
Addon Name: omnicd
Curseforge URL: https://www.curseforge.com/wow/addons/Omnicd

Since i dont know where to post a bug, Anti-Magic Shell seems to be bugged and not showing on the tracking frames.

**Comment by srhinos** [comment]
this isn't the place for this, nothing I can do but mirror the addon and wait for the author to update it. sorry
