### ISSUE TITLE
[REQ] Leatrix Plus & Leatrix Maps

### ISSUE THREAD

**Issue by Galetmonster** [curseforge-mirror/.github#113]
Addon Name: Leatrix Plus (The War Within)
Curseforge URL: https://www.curseforge.com/wow/addons/leatrix-plus

Addon Name: Leatrix Plus (Cataclysm Classic)
Curseforge URL: https://www.curseforge.com/wow/addons/leatrix-plus-cata

Addon Name: Leatrix Plus (Classic Era)
Curseforge URL: https://www.curseforge.com/wow/addons/leatrix-plus-classic

Addon Name: Leatrix Maps (The War Within)
Curseforge URL: https://www.curseforge.com/wow/addons/leatrix-maps

Addon Name: Leatrix Maps (Cataclysm Classic)
Curseforge URL: https://www.curseforge.com/wow/addons/leatrix-maps-cata

Addon Name: Leatrix Maps (Classic Era)
Curseforge URL: https://www.curseforge.com/wow/addons/leatrix-maps-classic

**Comment by srhinos** [comment]
leatrix DMCAs like crazy, have added them twice and both times got DMCA'd. Not adding, sorry. Go email the dude and tell him how unhinged he is I guess for close sourcing his mods and shutting down all comments lol
