### ISSUE TITLE
[REQ] New Addon Request

### ISSUE THREAD

**Issue by rbgdevx** [curseforge-mirror/.github#121]
Addon Name: Battleground Win Conditions
Curseforge URL: https://www.curseforge.com/wow/addons/battleground-win-conditions

Addon Name: Dynamic Movement Speed
Curseforge URL: https://www.curseforge.com/wow/addons/dynamic-movement-speed

Addon Name: Healer In Range
Curseforge URL: https://www.curseforge.com/wow/addons/healer-in-range

Addon Name: Auto Body Res
Curseforge URL: https://www.curseforge.com/wow/addons/auto-body-res

**Comment by srhinos** [comment]
Please open each of these as separate issues and I’ll tackle them!

**Comment by rbgdevx** [comment]
oh okay np
