### ISSUE TITLE
[REQ] New Addon Request - Battleground Win Conditions

### ISSUE THREAD

**Issue by rbgdevx** [curseforge-mirror/.github#125]
Addon Name: Battleground Win Conditions
Curseforge URL: https://www.curseforge.com/wow/addons/battleground-win-conditions

**Comment by rbgdevx** [comment]
im actually not sure what this repo does persay, i manually manage my addons in curse, wowi, and wago myself. i thought this addon would allow me to get addons on wowup, but if i had it one of of the other ones it would OOTB and wouldnt need to use this?

**Comment by srhinos** [comment]
Confused on what you’re confused about — this is a way to alert me on mirroring addons that are inaccessible to normal non-curseforge WoWUp or the CF client.

**Comment by rbgdevx** [comment]
oh okay got it, that makes more sense, then nevermind! all good, thank you for your service!
