### ISSUE TITLE
[REQ] Addon Removal Request

### ISSUE THREAD

**Issue by SLOKnightfall** [curseforge-mirror/.github#2]
Please remove "Better Wardrobe and Transmog Mirror" from this.  Permission was not granted to be hosted here.

**Comment by srhinos** [comment]
> Please remove "Better Wardrobe and Transmog Mirror" from this. Permission was not granted to be hosted here.

I removed the rehosted version from curseforge and swapped to a forked version of the github repo! 

Side note, highly suggest you [merge this PR](https://github.com/SLOKnightfall/BetterWardrobe/pull/271)!
