### ISSUE TITLE
[REQ] titan-panel

### ISSUE THREAD

**Issue by kingreboot** [curseforge-mirror/.github#22]
Addon Name: titan panel
Curseforge URL: https://www.curseforge.com/wow/addons/titan-panel

Only on Curse and wowinterface, but the wowinterface download is not being updated regularly

**Comment by srhinos** [comment]
It looks like all the files on WoWI match the CurseForge versions and are uploaded same day as the CF ones, confused whats missing or being updated late?

**Comment by srhinos** [comment]
Specifically this WoWI project:
https://www.wowinterface.com/downloads/info8092-TitanPanel.html#info

**Comment by kingreboot** [comment]
Sorry, I made a mistake looking at version numbers and realized wowup just has not shown the update. Your right and they do match so no need todo anything
