### ISSUE TITLE
[REQ] Easy Frames

### ISSUE THREAD

**Issue by nozzlegear** [curseforge-mirror/.github#24]
Addon Name: Easy Frames
Curseforge URL: https://www.curseforge.com/wow/addons/easy-frames

It looks like ~~somebody~~ the author has published this to wago and wowinterface, but it hasn't been updated since June 2022.

**Comment by srhinos** [comment]
Mirrored! Thanks for the note about the WoWI link too, checked and confirmed.

For future reference for the author / anyone curious:

[WoWI Link](https://www.wowinterface.com/downloads/info26346-EasyFrames.html)
[Author's comment about uploads](https://www.curseforge.com/wow/addons/easy-frames?comment=1507)
