### ISSUE TITLE
[REQ] New Addon Requests

### ISSUE THREAD

**Issue by j-mes** [curseforge-mirror/.github#25]
Addon Name: HandyNotes
Curseforge URL: https://www.curseforge.com/wow/addons/handynotes

Addon Name: Click Links
Curseforge URL: https://www.curseforge.com/wow/addons/clicklinks

Addon Name: BugSack
Curseforge URL: https://www.curseforge.com/wow/addons/bugsack

Addon Name: ItemLinkLevel
Curseforge URL: https://www.curseforge.com/wow/addons/itemlinklevel

Addon Name: Global Ignore List and Chat Spam Filter
Curseforge URL: https://www.curseforge.com/wow/addons/global-ignore-list

Addon Name: Method Raid Tools (MRT)
Curseforge URL: https://www.curseforge.com/wow/addons/method-raid-tools

Addon Name: MinimapButtonBag Reborn
Curseforge URL: https://www.curseforge.com/wow/addons/minimapbuttonbag-reborn-mmb-reborn

🙏

**Comment by srhinos** [comment]
Would prefer each addon as an individual ticket next time so I can label stuff better!


> Addon Name: HandyNotes Curseforge URL: https://www.curseforge.com/wow/addons/handynotes

[On WoWI here](https://www.wowinterface.com/downloads/info15716-HandyNotes.html)

> Addon Name: Click Links Curseforge URL: https://www.curseforge.com/wow/addons/clicklinks

[Mirrored -- find here!](https://github.com/curseforge-mirror/clicklinks)

> Addon Name: BugSack Curseforge URL: https://www.curseforge.com/wow/addons/bugsack

[On Github here](https://github.com/funkydude/BugSack)

> Addon Name: ItemLinkLevel Curseforge URL: https://www.curseforge.com/wow/addons/itemlinklevel

[Mirrored -- find here!](https://github.com/curseforge-mirror/itemlinklevel)

> Addon Name: Global Ignore List and Chat Spam Filter Curseforge URL: https://www.curseforge.com/wow/addons/global-ignore-list

[On WoWI here](https://www.wowinterface.com/downloads/info25034-GlobalIgnoreListClassic.html)

> Addon Name: Method Raid Tools (MRT) Curseforge URL: https://www.curseforge.com/wow/addons/method-raid-tools

[Already mirrored here](https://github.com/curseforge-mirror/method-raid-tools)

> Addon Name: MinimapButtonBag Reborn Curseforge URL: https://www.curseforge.com/wow/addons/minimapbuttonbag-reborn-mmb-reborn

[On Github here](https://github.com/pereira-a/MBB)

**Comment by srhinos** [comment]
For posterity:

Completed:
- clicklinks
- itemlinklevel

Duplicate:
- method-raid-tools

Won't Add:
- minimapbuttonbag-reborn-mmb-reborn
- global-ignore-list
- bugsack
- handynotes

**Comment by ljosberinn** [comment]
cheers & this is the correct link for global ignore list on wowi, you linked the classic one :) https://www.wowinterface.com/downloads/info23413-GlobalIgnoreListandSpamFilter.html
