### ISSUE TITLE
[REQ] Dialog Key

### ISSUE THREAD

**Issue by kingreboot** [curseforge-mirror/.github#29]
Addon Name: Dialog Key
Curseforge URL: https://www.curseforge.com/wow/addons/dialogkey-df

Still a new version of this addon, might host elsewhere but until then, curse only

**Comment by kingreboot** [comment]
Retrack this, author said he will do something about this over the weekend.

**Comment by srhinos** [comment]
Done!
https://github.com/curseforge-mirror/dialogkey-df
