### ISSUE TITLE
[REQ] RE: DejaCharacterStats: Addon Removal Request

### ISSUE THREAD

**Issue by dejoblue** [curseforge-mirror/.github#3]
Remove my addon DejaCharacterStats from this repository.

DejaCharacterStats' license is All Rights Reserved which is my explicit intent.

CurseForge's default license is All Rights Reserved (All addons on their site are All Rights Reserved unless a different license is explicitly designated)

DejaCharacterStats is hosted on my own website:

https://www.wowobserver.com/DCS/

DejaCharacterStats is hosted on Wago which means it is available on WoWUp as well:

https://addons.wago.io/user/Dejablue

https://addons.wago.io/addons/deja-character-stats

DejaCharacterStats is hosted on WoWInterface and available with their MMOMinion addon manager client:

https://www.wowinterface.com/downloads/author-22172.html

https://www.wowinterface.com/downloads/info24060-DejaCharacterStats.html

Thank you in advance for your timely removal of DejaCharacterStats from this repository:

https://github.com/curseforge-mirror

https://github.com/curseforge-mirror/dejacharacterstats

**Comment by srhinos** [comment]
Removed the repo! Thanks for the note and appreciate hosting in such a wide variety of places, totally didn't see the WoWI version before generating the repo

**Comment by dejoblue** [comment]
Thanks :)
