### ISSUE TITLE
[REQ]azeroth-pilot-reloaded

### ISSUE THREAD

**Issue by kingreboot** [curseforge-mirror/.github#30]
Addon Name: azeroth-pilot-reloaded
Curseforge URL: https://www.curseforge.com/wow/addons/azeroth-pilot-reloaded

New version of Azeroth auto pilot. I think they might make this addon downloadable via other host/github, but as of now. Curse only

**Comment by kingreboot** [comment]
Might want to recuse this or remove it to be replaced by new addon 

https://github.com/curseforge-mirror/azeroth-auto-pilot

**Comment by kingreboot** [comment]
Author of new addon added a todo tag to a open ticket asking for wowup support so might not need this addon hosted here

**Comment by srhinos** [comment]
gonna hold off on this, looks like their release process is super fucked up given their github has a v15 release 5 days ago thats not on CurseForge.

https://github.com/Rycia/azeroth-pilot-reloaded/releases

I'll check back on this closer to DF

**Comment by kingreboot** [comment]
Github link works now
