### ISSUE TITLE
Rerelease of unchanged addons

### ISSUE THREAD

**Issue by ljosberinn** [curseforge-mirror/.github#32]
Hi,

just noticed that apparently every 3 hours, addons are re-released, e.g. https://github.com/curseforge-mirror/mythic-dungeon-tools/releases/ despite there not being any chances in the source - MDT hasn't had a release for 3 days atm: https://github.com/Nnoggie/MythicDungeonTools/releases

Is this intended? I'm usually trying to keep up with changelog of addons hence my confusion :)

**Comment by srhinos** [comment]
yes! This is intended, WowUp is looking at manifests in each release to determine version numbers, not at the actual release itself.
