### ISSUE TITLE
[REQ] New Addon Request

### ISSUE THREAD

**Issue by j-mes** [curseforge-mirror/.github#33]
Addon Name: MouseoverActionBars - Mouseover Action Bars
Curseforge URL: https://www.curseforge.com/wow/addons/mouseoveractionbars-mouseover-action-bars

It isn't on GitHub as far as I can see

**Comment by srhinos** [comment]
Done!
https://github.com/curseforge-mirror/mouseoveractionbars-mouseover-action-bars
