### ISSUE TITLE
[REQ] Update to katy-stampwhistle

### ISSUE THREAD

**Issue by kingreboot** [curseforge-mirror/.github#34]
Addon Name: katy-stampwhistle
URL: https://github.com/curseforge-mirror/katy-stampwhistle

Katy Stamp whistle addon is now on Wago and does not need to be mirror here any longer 

https://addons.wago.io/addons/katy-stampwhistle

**Comment by srhinos** [comment]
I'm only removing addons that show up on github or wowinterface, unless this is on either it'll be staying up
