### ISSUE TITLE
[REQ] Prat

### ISSUE THREAD

**Issue by QartemisT** [curseforge-mirror/.github#37]
Addon Name: Prat-3.0 / Prat-tbc

Prat now officially uses github actions properly for github releases, is available on wowinterface, and will soon :tm: be avaialable on Wago :)

**Comment by srhinos** [comment]
I'll get around to removing them here soon, I swear!

**Comment by srhinos** [comment]
Finally got around to this after DF launch chilled out a bit, both repos are removed!

For anyone searching, I've verified [this repo](https://github.com/Legacy-of-Sylvanaar/prat-3-0) is getting proper deploys compatible with both Classic and Retail so please use it!
