### ISSUE TITLE
Possibly disable/filter Burning Crusade re-releases for Details?

### ISSUE THREAD

**Issue by ljosberinn** [curseforge-mirror/.github#46]
Ok so this is a fun one:

- Burning Crusade updates for Details! are no longer published since.. you can't officially play BC anymore
- https://github.com/curseforge-mirror/details/releases re-releases BC continously
- _technically_ the code from that release is fine to run on Retail too, BUT
  - its outdated by now, since Details! doesn't publish Curseforge releases for BC anymore due to redundancy as of above
  - ajour will just happily pick the first .zip found in the release page meaning its permanently reverting to an old, technically unmaintained version of Details! of 10304 while 10337 is out by now
- the only alternative for Retail/Wrath players atm is to simply not use the curseforge mirror and manually update

This kind of plays into the general issue of continously re-releasing unchanged versions (can't find the issue 🤔) which I guess could prevent this too but could we possibly disable the `-bc` file mirror for Details! ?

**Comment by srhinos** [comment]
Oh wow that's wild! Okay so I think this definitely sounds like a big on the Ajour side of things, it should be looking for the expansion's extension, wrath being "-wotlk" and retail not having any as that's the behavior cursebreaker and Wowup go by. Is this an issue on Ajour's issue tracker by any chance? I'm happy to temporarily disable the bc flag but will re-enable in the future if/when a SoM for BC drops so might be smart to get the long term fix in with ajour!

**Comment by ljosberinn** [comment]
ajour is sadly discontinued for over a year, I'm maintaining a custom fork however and I've found the issue: the releases are detected based on Flavor and the details release ends with `-bc`, not `-bcc` or `-tbc` so I'll fix that locally in ajour. fwiw, do you control the release asset generation naming or is that on details end?

**Comment by ljosberinn** [comment]
fixed locally I guess 😅

**Comment by srhinos** [comment]
> ajour is sadly discontinued for over a year, I'm maintaining a custom fork however and I've found the issue: the releases are detected based on Flavor and the details release ends with `-bc`, not `-bcc` or `-tbc` so I'll fix that locally in ajour. fwiw, do you control the release asset generation naming or is that on details end?

I control naming, setting it myself in case addon authors don't. There wasn't a real standard especially among authors who didn't want to support outside curseforge so I just append stuff on in my script. Should be visible in main.py somewhere!
