### ISSUE TITLE
[REQ] New Addon Request

### ISSUE THREAD

**Issue by thats-how-you-get-ants** [curseforge-mirror/.github#47]
Addon Name: RCLootCouncil
Curseforge URL: https://www.curseforge.com/wow/addons/rclootcouncil

I don't see them on wowinterface.
They are on github but not in a way that imports to wowup: https://github.com/evil-morfar/RCLootCouncil2

**Comment by srhinos** [comment]
Already mirrored [here](https://github.com/curseforge-mirror/rclootcouncil)

**Comment by thats-how-you-get-ants** [comment]
xoxo
