### ISSUE TITLE
[REQ] sArena Updated

### ISSUE THREAD

**Issue by nozzlegear** [curseforge-mirror/.github#49]
Addon Name: sArena Updated (Retail & TBC)
Curseforge URL: https://www.curseforge.com/wow/addons/sarena-updated-retail-tbc

Would love to have this one available!

**Comment by srhinos** [comment]
Sorry, been busy for a bit so just got around to filling out back-requests.

Mirrored [here](https://github.com/curseforge-mirror/sarena-updated-retail-tbc)!

**Comment by nozzlegear** [comment]
No worries, thanks a bunch!
