### ISSUE TITLE
[REQ] Addon Removal Request

### ISSUE THREAD

**Issue by Numynum** [curseforge-mirror/.github#60]
[Macro Toolkit](https://github.com/curseforge-mirror/macro-toolkit/releases) is officially available at https://github.com/NumyAddon/MacroToolkit
while the license does not expressly forbid redistribution, it's better for the users and the project, if only official sources are used for updates

**Comment by srhinos** [comment]
Nice! I didn’t notice you started distributing this on GitHub! I’ll remove it then, ty for the ticket
