### ISSUE TITLE
CopyPasta addon request

### ISSUE THREAD

**Issue by ImmutableBug** [curseforge-mirror/.github#64]
Addon Name: CopyPasta
Curseforge URL: https://www.curseforge.com/wow/addons/copypasta

**Comment by srhinos** [comment]
This addon is specifically super out of date. CopyPasta2 exists but only on TukUI which died recently. I went ahead and forked and fixed up the code for it [here](https://github.com/curseforge-mirror/CopyPasta2), should be a functioning drop-in replacement for OG copypasta
