### ISSUE TITLE
[REQ] HandyNotes: Draenor

### ISSUE THREAD

**Issue by ilu33** [curseforge-mirror/.github#66]
Addon Name: HandyNotes: Draenor
Curseforge URL: https://www.curseforge.com/wow/addons/handynotes-draenor

Has MIT license.

**Comment by srhinos** [comment]
tysm for the license call outs, sorry for being slow to get to this. Was done with WoW for a bit. Have this mirrored [here](https://github.com/curseforge-mirror/handynotes-draenor)
