### ISSUE TITLE
[REQ] ImprovedStableFrame

### ISSUE THREAD

**Issue by ilu33** [curseforge-mirror/.github#67]
Addon Name: ImprovedStableFrame
Curseforge URL: https://www.curseforge.com/wow/addons/improved-stable-frame
License GPL
Is already on github https://github.com/ascott18/ImprovedStableFrame
but lacks correct release file

**Comment by srhinos** [comment]
Done [here](https://github.com/curseforge-mirror/improved-stable-frame)
