### ISSUE TITLE
[REQ] Battle Pet Completionist

### ISSUE THREAD

**Issue by ilu33** [curseforge-mirror/.github#68]
Addon Name: Battle Pet Completionist
Curseforge URL: https://legacy.curseforge.com/wow/addons/battle-pet-completionist
License GPL
already on github https://github.com/GurliGebis/WoWAddon-BattlePetCompletionist
but without release file

**Comment by srhinos** [comment]
done [here](https://github.com/curseforge-mirror/battle-pet-completionist)
