### ISSUE TITLE
[REQ] New Addon Request - omnisort

### ISSUE THREAD

**Issue by jtrull** [curseforge-mirror/.github#76]
Addon Name: OmniSort - Party Group Sorter
Curseforge URL: https://www.curseforge.com/wow/addons/omnisort

**Comment by srhinos** [comment]
done [here](https://github.com/curseforge-mirror/omnisort)!

**Comment by srhinos** [comment]
nvm it looks like the addon was completely removed from curseforge. I've gone ahead and deleted it from here too since there was nothing to pull. RIP it :(
