### ISSUE TITLE
[REQ] Leatrix Plus (Dragonflight & The War Within)

### ISSUE THREAD

**Issue by peterweissbier** [curseforge-mirror/.github#94]
Addon Name: Leatrix Plus (Dragonflight & The War Within)
Curseforge URL: https://www.curseforge.com/wow/addons/leatrix-plus

**Comment by srhinos** [comment]
leatrix is a prick who DMCAs it every time I mirror it. I have it privately mirrored but can't really give anyone access easily. Sorry :(
