### ISSUE TITLE
[REQ] Leatrix Maps (Dragonflight & The War Within)

### ISSUE THREAD

**Issue by peterweissbier** [curseforge-mirror/.github#95]
Addon Name: Leatrix Maps (Dragonflight & The War Within)
Curseforge URL: https://www.curseforge.com/wow/addons/leatrix-maps

**Comment by srhinos** [comment]
leatrix is a prick who DMCAs it every time I mirror it. I have it privately mirrored but can't really give anyone access easily. Sorry :(

**Comment by peterweissbier** [comment]
ah damn, thanks for the info
